version: "3.3"

services:
    mysql:
        image: percona:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "items"
        ports:
            - 3306:3306

    dbapitest:
        image: studentaleksandr/dbtestapi:latest
        ports:
        - 3000:3000